# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76105b0c9599eedfb96975c9d946ad3131ce7983ac0059c6e5ed9b9b1d661afba07afdc33adddbfb75e01669d0483e128331f8daa5677d5aab8778f6120904d8

test:
  secret_key_base: 3fcbfa5514368fca6c4336ec2fc1136c364816fd104bb9ebc3e27d6f19573fe19d641cf91209d9d920ffa66fbcd703c0dbab7663b1049d8d373561c6d981ba59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
